blank_issues_enabled: false
contact_links:
  - name: Discord Chat
    url: https://discord.gg/JDa79KXUw9
    about: Ask questions and discuss with other developers in real time.
  - name: Questions & Discussions
    url: https://github.com/ChatterChats/pySpaceTrader/discussions
    about: Use GitHub discussions for message-board style questions and discussions.
